In [45]:
#oferta um grande número de funções para cálculos númericos.
#DIMENSÕES = EIXOS
#grande volumes de informações
#NUMPY É BOM PARA PROCESSAMENTO MAIORES, PARRUDOS, ETCS

In [4]:
#importar a lib
import numpy as np

In [6]:
print( np.__version__ )

1.21.6


In [7]:
#criar uma matriz com um eixo/dimensão
Array = np.array([10, 20, 30, 40, 50])
Array

array([10, 20, 30, 40, 50])

In [8]:
type(Array)

numpy.ndarray

In [13]:
#criando uma matriz com dois eixos
DuasDim = np.array(
    [[10, 9, 8, 7, 6],
    [5,4,3,2,1]]
    )

print(DuasDim)
#para esse procedimento, dentro dos parenteses são dois colchetes, um para os eixos
# e o segundo para abranger os dois eixos juntos

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [14]:
#3 dimensoes
TresDim = np.array([
    [15,14,13,12,11],
    [10, 9, 8, 7, 6],
    [5,4,3,2,1]
])

print(TresDim)

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [21]:
#teste
Teste_Stress = np.arange(1000000)
Teste_Stress02 = np.arange(5000000)
Teste_Stress03 = np.arange(10000000)
Teste_Stress04 = np.arange(50000000)
print(len(Teste_Stress), len(Teste_Stress02),len(Teste_Stress03),len(Teste_Stress04),)

1000000 5000000 10000000 50000000


In [20]:
#teste de processamento
%time for loop in Teste_Stress: pass # %time = quanto tempo demora para verificar a memoria

CPU times: user 68.7 ms, sys: 0 ns, total: 68.7 ms
Wall time: 71.1 ms


In [22]:
#teste de processamento- 02
%time for loop in Teste_Stress02: pass

CPU times: user 341 ms, sys: 0 ns, total: 341 ms
Wall time: 342 ms


In [24]:
#teste processamento 03
%time for loop in Teste_Stress03: pass

CPU times: user 673 ms, sys: 0 ns, total: 673 ms
Wall time: 675 ms


In [25]:
#teste processamento 04
%time for loop in Teste_Stress04: pass

CPU times: user 3.34 s, sys: 2.02 ms, total: 3.34 s
Wall time: 3.35 s


In [27]:
#acessar a array
Array

array([10, 20, 30, 40, 50])

In [28]:
Array[2]

30

In [29]:
Array[-1]

50

In [31]:
print(Array[1], Array[4])
Array[1] + Array[4]

20 50


70

In [32]:
Array[1] > Array[0]

True

In [33]:
Array[1] > Array[2]

False

In [34]:
for loop in Array:
  print(loop)

10
20
30
40
50


In [35]:
DuasDim

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [36]:
DuasDim.shape

(2, 5)

In [37]:
for loop in DuasDim:
  print(loop)

[10  9  8  7  6]
[5 4 3 2 1]


In [38]:
#nesse caso de dois eixos, ao imrprimir por meio do for, ao inves de apresentar os resultados em linha por linha
#o programa apresenta o eixo inteiro, enquanto o de uma dimensão apresenta o resultado em linha por linha

In [41]:
for loop in DuasDim:
  print(loop) #esse print não precisava, mas serviu para ilustrar o funcionamento do for.
  for interno in loop:
    print(interno)

[10  9  8  7  6]
10
9
8
7
6
[5 4 3 2 1]
5
4
3
2
1


In [42]:
import pandas as pd

In [44]:
pd.DataFrame( Array, columns = {'Vetor de 1 Eixo'})

Vetor de 1 Eixo
0               10
1               20
2               30
3               40
4               50

In [48]:
pd.DataFrame(DuasDim)

0  1  2  3  4
0  10  9  8  7  6
1   5  4  3  2  1